name: Publish/Upload dotnet package on release

# PLEASE NOTE: PUBLISHING/DEPLOYMENT
# Release is to be created manually at GitHub releases management page
# - release name usually contains "v1.2.3"
# After creating a GitHub release, following actions will automatically run:
# 1. NuGet package (version as defined in VS.Net project property "package version")
# 2. Attaching of compiled binaries to GitHub release

on:
  release:
    types: [created]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Name of project configuration for build as well as name of the bin output subdirectory (both must match for "dotnet pack" to find compiled files!)
  BUILD_CONFIGURATION: Release
  # Name of build project which creates required output for packaging/deployment
  BUILD_PROJECT: CompuMaster.Dms.Providers/CompuMaster.Dms.Providers.vbproj
  BUILD_PROJECT2: CompuMaster.Dms.BrowserUI/CompuMaster.Dms.BrowserUI.vbproj
  # Name of directory (e.g. "bin") containing the subdirectory (e.g. "CI_CD") with all output files (*.dll)
  BUILD_OUTPUT_BASEDIR: CompuMaster.Dms.Providers/bin
  BUILD_OUTPUT_BASEDIR2: CompuMaster.Dms.BrowserUI/bin
  BUILD_OUTPUT_BASEDIR3: CompuMaster.Dms.TestDemo.ScopevisioTeamwork/bin
  BUILD_OUTPUT_BASEDIR4: CompuMaster.Dms.TestDemo.WebDav/bin


jobs:
    publish:
        runs-on: windows-latest
        #if: false # always skip job

        env:
          VersionPrefix: ${{  github.ref_name }}

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 8.0.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration=${{env.BUILD_CONFIGURATION}} --no-restore 

            - name: Pack binaries CompuMaster.Dms.Providers
              run: Compress-Archive -DestinationPath bin-providers.zip ${{env.BUILD_OUTPUT_BASEDIR}}/${{env.BUILD_CONFIGURATION}}

            - name: Pack binaries CompuMaster.Dms.BrowserUI
              run: Compress-Archive -DestinationPath bin-browserui.zip ${{env.BUILD_OUTPUT_BASEDIR2}}/${{env.BUILD_CONFIGURATION}}

            - name: Pack binaries CompuMaster.Dms.TestDemo.ScopevisioTeamwork
              run: Compress-Archive -DestinationPath bin-scopevisio-teamwork.zip ${{env.BUILD_OUTPUT_BASEDIR3}}/${{env.BUILD_CONFIGURATION}}

            - name: Pack binaries CompuMaster.Dms.TestDemo.WebDav
              run: Compress-Archive -DestinationPath bin-webdav.zip ${{env.BUILD_OUTPUT_BASEDIR4}}/${{env.BUILD_CONFIGURATION}}

            - name: Publish binaries CompuMaster.Dms.Providers
              uses: softprops/action-gh-release@v1
              with:
                files: "bin-providers.zip"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish binaries CompuMaster.Dms.BrowserUI
              uses: softprops/action-gh-release@v1
              with:
                files: "bin-browserui.zip"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish binaries CompuMaster.Dms.TestDemo.ScopevisioTeamwork
              uses: softprops/action-gh-release@v1
              with:
                files: "bin-scopevisio-teamwork.zip"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish binaries CompuMaster.Dms.TestDemo.WebDav
              uses: softprops/action-gh-release@v1
              with:
                files: "bin-webdav.zip"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Pack CompuMaster.Dms.Providers
              run: dotnet pack --no-build --configuration=${{env.BUILD_CONFIGURATION}} ${{env.BUILD_PROJECT}} --output .  

            - name: Pack CompuMaster.Dms.BrowserUI
              run: dotnet pack --no-build --configuration=${{env.BUILD_CONFIGURATION}} ${{env.BUILD_PROJECT2}} --output .  

            - name: PushNuget CompuMaster.Dms.Providers + CompuMaster.Dms.BrowserUI
              run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate 

            - name: Publish Package Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Nupkg Artifacts
                path: ./**/*.nupkg
